### ISSUE TITLE
Difference between ZOSMD and ZOPSGD?

### ISSUE THREAD

**Issue by lin2020** [KaidiXu/ZO-AdaMM#1]
Hi, what is the difference between ZOSMD and ZOPSGD?
I look at the code in imagenet_blackBox_attack2.py and find that ZOSMD and ZOPSGD only diff in https://github.com/KaidiXu/ZO-AdaMM/blob/d7bf2830f4ac9eb5154e0718579c455c0bec7e94/imagenet_blackBox_attack2.py#L235 and https://github.com/KaidiXu/ZO-AdaMM/blob/d7bf2830f4ac9eb5154e0718579c455c0bec7e94/imagenet_blackBox_attack2.py#L243. 
It seems that the difference between ZOSMD and ZOPSGD is only learning rate.

**Comment by KaidiXu** [comment]
Hi,

You are right, under euclidean distance they are same, only the learning rates are different!
